export const FAN_STATUS_NOTIFICATION = 'FAN_STATUS_NOTIFICATION';
export const LIGHTNING_STATUS_NOTIFICATION = 'LIGHTNING_STATUS_NOTIFICATION';
export const WATER_PUMP_STATUS_NOTIFICATION = 'WATER_PUMP_STATUS_NOTIFICATION';
export const DE_HUMIDIFIER_STATUS_NOTIFICATION = 'DE_HUMIDIFIER_STATUS_NOTIFICATION';